workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.fadhakkir.app
    scripts:
      - name: Sync Capacitor
        script: |
          npx cap sync
      - name: Build iOS project
        script: |
          npx cap open ios && npx cap build ios
    artifacts:
      - build/ipa/*.ipa